package springboot.demo.bean;

public class Novel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.id
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.novel_name
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    private String novelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.description
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel.ver
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    private Integer ver;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.id
     *
     * @return the value of novel.id
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.id
     *
     * @param id the value for novel.id
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.novel_name
     *
     * @return the value of novel.novel_name
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    public String getNovelName() {
        return novelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.novel_name
     *
     * @param novelName the value for novel.novel_name
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    public void setNovelName(String novelName) {
        this.novelName = novelName == null ? null : novelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.description
     *
     * @return the value of novel.description
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.description
     *
     * @param description the value for novel.description
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel.ver
     *
     * @return the value of novel.ver
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    public Integer getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel.ver
     *
     * @param ver the value for novel.ver
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    public void setVer(Integer ver) {
        this.ver = ver;
    }
}