server: 
  port: 443
  ssl:
    key-store: classpath:tomcat_https.keystore
    key-store-type: JKS
    key-alias: tomcat_https
    key-password: 123456
spring:
  application:
    name: consumer
  main:
    allow-bean-definition-overriding: true
  redis:
#    host: 124.223.61.143
#    host: 192.168.1.38
    host: 119.91.195.175
    port: 26380
    password: bAqHqOFJHJ*Z@wIRk6bS
    cluster:
      nodes: 192.168.0.102:7001,192.168.0.102:7002,192.168.0.102:7003,192.168.0.102:7004,192.168.0.102:7005,192.168.0.102:7006
      max-redirects: 6
    maxIdle: 300
    maxActive: 600
    maxWait: 1000
    testOnBorrow: true
    timeout: 3000
logging:
  config: classpath:logging-config.xml

websocket:
  url: ws://127.0.0.1:7070/websocket

mybatis:
  mapperLocations: classpath:springboot/demo/bean/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
      sensitive: false
