server: 
  port: 443
  ssl:
    key-store: classpath:tomcat_https.keystore
    key-store-type: JKS
    key-alias: tomcat_https
    key-password: 123456
spring:
  application:
    name: consumer
  main:
    allow-bean-definition-overriding: true
  redis:
#    host: 192.168.1.36
    host: 119.91.195.175
    port: 6380
    password: 123456
    maxIdle: 300
    maxActive: 600
    maxWait: 1000
    testOnBorrow: true
logging:
  config: classpath:logging-config.xml

websocket:
  url: ws://127.0.0.1:7070/websocket

mybatis:
  mapperLocations: classpath:springboot/demo/bean/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
      sensitive: false
