package springboot.demo.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import springboot.demo.bean.Novel;
import springboot.demo.bean.NovelExample;

public interface NovelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    int countByExample(NovelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    int deleteByExample(NovelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    int insert(Novel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    int insertSelective(Novel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    List<Novel> selectByExample(NovelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    Novel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Novel record, @Param("example") NovelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    int updateByExample(@Param("record") Novel record, @Param("example") NovelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    int updateByPrimaryKeySelective(Novel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table novel
     *
     * @mbggenerated Sat May 23 17:13:18 CST 2020
     */
    int updateByPrimaryKey(Novel record);
}